DROP TABLE category IF EXISTS;

CREATE TABLE category  (
category_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(20),
type VARCHAR(20),
characteristics VARCHAR(30)
);

DROP TABLE game IF EXISTS;

CREATE TABLE game (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title VARCHAR(50),
age INT,
stock INT
);
